# .gitlab-ci.yml in data-repo

stages:
  - build
  - deploy
  - trigger_site_build

variables:
  GIT_STRATEGY: fetch

# Job 1: Build
build_job:
  stage: build
  image: python:3.8
  only:
    - develop
  script:
    - pip install --upgrade pip
    - pip install -r scripts/requirements.txt
    - python scripts/build_data.py
    - cp public/robots-staging.txt _site/robots.txt
  artifacts:
    paths:
      - _site
    expire_in: 1 hour

# Job 2: Deploy zu GitLab Pages (optional, falls notwendig)
pages:
  stage: deploy
  image: alpine:latest
  dependencies:
    - build_job
  script:
    - apk add --no-cache rsync
    - mkdir -p public
    - rsync -av _site/ public/
  artifacts:
    paths:
      - public
  only:
    - develop

# Job 3: Trigger Site Build in site-repo
trigger_site_build:
  stage: trigger_site_build
  image: alpine:latest
  dependencies:
    - build_job
    - pages
  only:
    - develop
  script:
    - apk add --no-cache curl
    - |
      if [ -z "${SITE_TRIGGER_TOKEN}" ]; then
        echo "SITE_TRIGGER_TOKEN ist nicht gesetzt"
        exit 1
      else
        echo "SITE_TRIGGER_TOKEN ist gesetzt"
      fi
    - echo "Warte 4 Minuten auf die Bereitstellung der Staging-Daten..."
    - sleep 240
    - |
      curl --request POST \
        --form "token=${SITE_TRIGGER_TOKEN}" \
        --form "ref=develop" \
        "https://gitlab.opencode.de/api/v4/projects/4128/trigger/pipeline"
